#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="/usr/local/bin/scripts:$PATH"
#export PATH="$HOME/bin"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
export PATH="/Users/aidanmatchette/code/rust/binaries":$PATH
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export PATH=$PATH:(go env GOPATH)/bin

export FZF_DEFAULT_OPTS='
  --ansi
  --layout=reverse
  --height=40%
  --border
  --margin=1%,1%
  --prompt="> "'

export LDFLAGS="-L/opt/homebrew/opt/postgresql@15/lib"
export CPPFLAGS="-I/opt/homebrew/opt/postgresql@15/include"

export PKG_CONFIG_PATH="/opt/homebrew/opt/postgresql@15/lib/pkgconfig"

export LS_COLORS="$(vivid generate ~/.config/colors/catppuccin-macchiato.yml)"
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

export PGDATA=/opt/homebrew/var/postgres@14
