#!/bin/sh

if [ -z "$TMUX" ]; then

    ZOXIDE_RESULT=$(zoxide query -l | fzf)

    if [ -z "$ZOXIDE_RESULT" ]; then
        exit 0
    fi

    FOLDER=$(basename $ZOXIDE_RESULT)

    SESSION=$(tmux list-sessions | grep $FOLDER | awk '{print $1}')
    SESSION=${SESSION//:/}

    if [ -z "$SESSION" ]; then
        cd $ZOXIDE_RESULT

        tmux new-session -s $FOLDER
    else
        tmux attach -t $SESSION
    fi
else

    ZOXIDE_RESULT=$(zoxide query -l | fzf)

    if [ -z "$ZOXIDE_RESULT" ]; then
        exit 0
    fi

    FOLDER=$(basename $ZOXIDE_RESULT)

    SESSION=$(tmux list-sessions | grep $FOLDER | awk '{print sessions}')
    SESSION=${SESSION//:/}

    if [ -z "$SESSION" ]; then
        cd $ZOXIDE_RESULT

        tmux new-session -d -s $FOLDER
        tmux switch-client -t $FOLDER
    else
        tmux switch-client -t $FOLDER
    fi
fi


